# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "5432:5432"

  postgres:
    image: postgres:10-alpine
    environment:
      DATABASE_URL: postgres://postgres:123@127.0.0.1:5432/test_app