import { NAME } from './constants'

export const LOAD_UP_LIST_MESSAGES = `${NAME}/LOAD_UP_LIST_MESSAGES`
export const LOAD_UP_LIST_MESSAGES_FAILED = `${NAME}/LOAD_UP_LIST_MESSAGES_FAILED`
export const LOAD_UP_LIST_MESSAGES_SUCCEEDED = `${NAME}/LOAD_UP_LIST_MESSAGES_SUCCEEDED`

export const UPDATE_NEW_MESSAGE = `${NAME}/UPDATE_NEW_MESSAGE`

export const REFRESH_BASE_COMPONENT = `${NAME}/REFRESH_BASE_COMPONENT`