import { NAME } from './constants';

export const LOAD_UP_LIST_USERS = `${NAME}/LOAD_UP_LIST_USERS`;
export const LOAD_UP_LIST_USERS_FAILED = `${NAME}/LOAD_UP_LIST_USERS_FAILED`;
export const LOAD_UP_LIST_USERS_SUCCEEDED = `${NAME}/LOAD_UP_LIST_USERS_SUCCEEDED`;

export const REFRESH_BASE_COMPONENT = `${NAME}/REFRESH_BASE_COMPONENT`;