import { NAME } from './constants';

export const LOAD_UP_LIST_ROLES = `${NAME}/LOAD_UP_LIST_ROLES`;
export const LOAD_UP_LIST_ROLES_FAILED = `${NAME}/LOAD_UP_LIST_ROLES_FAILED`;
export const LOAD_UP_LIST_ROLES_SUCCEEDED = `${NAME}/LOAD_UP_LIST_ROLES_SUCCEEDED`;

export const REFRESH_BASE_COMPONENT = `${NAME}/REFRESH_BASE_COMPONENT`;