import { NAME } from './constants'

export const LOGIN_FORM_USER = `${NAME}/LOGIN_FORM_USER`
export const LOGIN_FORM_USER_FAILED = `${NAME}/LOGIN_FORM_USER_FAILED`
export const LOGIN_FORM_USER_SUCCEEDED = `${NAME}/LOGIN_FORM_USER_SUCCEEDED`

export const LOGOUT_FORM_USER = `${NAME}/LOGOUT_FORM_USER`

export const REFRESH_BASE_COMPONENT = `${NAME}/REFRESH_BASE_COMPONENT`